GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
DELETE http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "VS Code",
    "number": "12345-678"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ada Lovelace",
    "number": "12345-678"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "47320"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "No number",
    "number": ""
}

###
GET https://phonebook-backend-server.herokuapp.com/api/persons

###
GET http://localhost:3001/api/notes/5c41c90e84d891c15dfa3431

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "573209868975"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hollas",
    "number": "573209658957"
}
